/* ============================================================
   selector.js — robust CSS / XPath selector generation.
   Reuses the same logic as src/core/LiveBrowser.ts PICKER_SCRIPT
   (Step 12) so selectors generated by the extension match those
   generated by the server-side Live Browser View.
   Exposes window.ABSelector = { cssPath, xPath }.
   No external deps; safe to inject into any page.
   ============================================================ */
(function () {
  'use strict';
  if (window.ABSelector) return;

  function esc(s) {
    if (window.CSS && CSS.escape) return CSS.escape(s);
    // Minimal fallback for older engines.
    return String(s).replace(/[^a-zA-Z0-9_-]/g, function (c) {
      return '\\' + c;
    });
  }

  // Build a reasonably-short, stable CSS path (id shortcut, class hints,
  // :nth-of-type disambiguation), capped at 6 levels.
  function cssPath(el) {
    if (!(el instanceof Element)) return '';
    if (el.id) return '#' + esc(el.id);
    var parts = [];
    while (el && el.nodeType === 1 && parts.length < 6) {
      var sel = el.nodeName.toLowerCase();
      if (el.id) { parts.unshift('#' + esc(el.id)); break; }
      var cls = (el.getAttribute('class') || '').trim().split(/\s+/).filter(Boolean).slice(0, 2);
      if (cls.length) {
        sel += '.' + cls.map(function (c) { return esc(c); }).join('.');
      }
      var parent = el.parentNode;
      if (parent) {
        var sibs = Array.prototype.filter.call(parent.children, function (c) {
          return c.nodeName === el.nodeName;
        });
        if (sibs.length > 1) {
          sel += ':nth-of-type(' + (sibs.indexOf(el) + 1) + ')';
        }
      }
      parts.unshift(sel);
      el = el.parentElement;
    }
    return parts.join(' > ');
  }

  function xPath(el) {
    if (el && el.id) return '//*[@id="' + el.id + '"]';
    var parts = [];
    while (el && el.nodeType === 1) {
      var idx = 1, sib = el.previousSibling;
      while (sib) {
        if (sib.nodeType === 1 && sib.nodeName === el.nodeName) idx++;
        sib = sib.previousSibling;
      }
      parts.unshift(el.nodeName.toLowerCase() + '[' + idx + ']');
      el = el.parentElement;
    }
    return '/' + parts.join('/');
  }

  window.ABSelector = { cssPath: cssPath, xPath: xPath };
})();
